### ISSUE TITLE
Create icon for the app

### ISSUE THREAD

**Issue by leav** [leav/SquareJam18_ThisIsFine#2]
Currently the app is the default unity icon when it appears on desktop and android. We want to have a 1024x1024 icon, which will automatically get shrinked for different platforms.

**Comment by leav** [comment]
we could also just make it 256 x 256 if 1024 making the file size too big.

**Comment by ghost** [comment]
![find_dog](https://user-images.githubusercontent.com/18133350/38355657-72491b58-3872-11e8-9bb8-b95eec8381fb.png)

**Comment by ghost** [comment]
I just enlarged the dog.

**Comment by leav** [comment]
👍

**Comment by leav** [comment]
fixed in 394f5a72ff033156511bbc7b87000b4ee7f9bf5d
